#---------------------------------------Custom Exporter-----------------#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: mayurhingnekar/java-exporter:latest     # update metrics via http://svc/updatemetrics?queued_req=6 and get metrices via http://cs-svc/metrics
        ports:
        - name: web
          containerPort: 7777
---
#---------------------------------------Custom Exporter svc----------------#
kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  selector:
    app: example-app
  ports:
  - name: web
    port: 7777
---
#---------------------------------------Custom Exporter svc monitor 3rd party-----------------#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
---
#---------------------------------------Promethues Server Part starts-----------------#
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
      - name: example-app
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
---
#---------------------------------------Prometheus Instance opertor component-----------------#
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  resources:
    requests:
      memory: 400Mi
---
#---------------------------------------Prometheus server svc-----------------#
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus